$ANSIBLE_VAULT;1.1;AES256
63356439316138396630356335373561623765633063656665303463636632396539386530393261
6466656136343232646631646434636636306536393036630a313165333831373939336234643138
65396138356230653934363533623266376464363432653465303764366466353761323435613636
6331326666303363370a366665623265343034383430646631663839386262323532353833623264
65323731623862356336333633333036336233346236373633396466643635353863386666383439
63663035323531316432666139313638313064313038316566346166643837353465333135376663
30306635646565626135313037613339626163363238663863653865346663323031306437303737
30663237643166626138316164323438646261636330363363393563316637353536643765346161
38653762336437616634303861396162343333343866643936616462393962376530383135646538
64336462356531326234633963643465376632313162316262353462333361373038616366613133
33626334613863633761323762373433666337333630633634306363643134396263326130333362
36613764396239663034363465313464313435633162303932373732306263313237326363363464
37313734396134356337346338643731633334376331356661333566323131663532353962663537
35363138306566333736316166303334313337346536333639353765646532363464376564363264
30393632613561333235336532366265646533313565616333623164316130346132363935323437
35366233326334343264633433643430613563313866313136656363623838356563303731343063
65313631346235393334303862636665653031613062383335363534626561343739366638636237
38653038316431313535643433303162333563653961653561333664626266363135646163343238
66383564393737616538333330336133646666396439353534616366306338353165353831636266
33353037366631383936623165356231343539353538333631663566313230623737323936313531
3831
