docker_config_root: "/etc/docker"

homepage_hostname: "home.mtx.dev"
homepage_allowed_hosts: "home.mtx.dev"

uptime_kuma_hostname: "status.mtx.dev"

apache_hostname: "mtx.dev"

portainer_hostname: "portainer.mtx.dev"

traefik_hostname: "monitor.mtx.dev"

vpn_hostname: "vpn.mtx.dev"

database_hostname: "database.mtx.dev"

timezone: "Europe/Paris"
domain: "mtx.dev"
