ports:
  homepage:
    http: 3000
  uptime_kuma:
    http: 3001
  apache:
    http: 80
  portainer:
    http: 9000
  traefik:
    http: 80
    https: 443
    openvpn: 1194
    database: 5010
  database:
    tcp: 5432 
  pgadmin:
    http: 80
  crowdsec:
    http: 8080
  metabase:
    http: 3000
  prometheus:
    http: 9090
  alertmanager:
    http: 9093
  grafana:
    http: 3000
  loki:
    http: 3100
  node_exporter:
    http: 9100
  cadvisor:
    http: 8081
  alertrelay:
    http: 8082
  n8n:
    http: 5678