$ANSIBLE_VAULT;1.1;AES256
39396266383532643236626563626534313339343963356461643363653636663531616332666661
3366666433336434393830366161316266643034313463320a386662396562613433623537616430
30663732616364656132623962633266626337343961626332303964643436633933363434383137
3630643866313465640a396466376237626432653432333731323963363538613362663766666561
31336264316333333738306266393036333536343139396530346334306130326530343665653233
35386632633032326432333735353531363833393762333461383031393430306536333761343038
63613738373533386361633764383634633638323533353666646530363865646162353032393930
39333631323161353435613065653834623734383765376430356332626639343039353636623030
3630
